# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baloo/documents/LopetteRobot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baloo/documents/LopetteRobot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baloo/documents/LopetteRobot/CMakeFiles /home/baloo/documents/LopetteRobot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baloo/documents/LopetteRobot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LopetteRobot

# Build rule for target.
LopetteRobot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LopetteRobot
.PHONY : LopetteRobot

# fast build rule for target.
LopetteRobot/fast:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/build
.PHONY : LopetteRobot/fast

src/BindingAVR/BindingAVR.o: src/BindingAVR/BindingAVR.c.o
.PHONY : src/BindingAVR/BindingAVR.o

# target to build an object file
src/BindingAVR/BindingAVR.c.o:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/BindingAVR/BindingAVR.c.o
.PHONY : src/BindingAVR/BindingAVR.c.o

src/BindingAVR/BindingAVR.i: src/BindingAVR/BindingAVR.c.i
.PHONY : src/BindingAVR/BindingAVR.i

# target to preprocess a source file
src/BindingAVR/BindingAVR.c.i:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/BindingAVR/BindingAVR.c.i
.PHONY : src/BindingAVR/BindingAVR.c.i

src/BindingAVR/BindingAVR.s: src/BindingAVR/BindingAVR.c.s
.PHONY : src/BindingAVR/BindingAVR.s

# target to generate assembly for a file
src/BindingAVR/BindingAVR.c.s:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/BindingAVR/BindingAVR.c.s
.PHONY : src/BindingAVR/BindingAVR.c.s

src/Commande/Commande.o: src/Commande/Commande.c.o
.PHONY : src/Commande/Commande.o

# target to build an object file
src/Commande/Commande.c.o:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Commande/Commande.c.o
.PHONY : src/Commande/Commande.c.o

src/Commande/Commande.i: src/Commande/Commande.c.i
.PHONY : src/Commande/Commande.i

# target to preprocess a source file
src/Commande/Commande.c.i:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Commande/Commande.c.i
.PHONY : src/Commande/Commande.c.i

src/Commande/Commande.s: src/Commande/Commande.c.s
.PHONY : src/Commande/Commande.s

# target to generate assembly for a file
src/Commande/Commande.c.s:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Commande/Commande.c.s
.PHONY : src/Commande/Commande.c.s

src/Parse/Parse.o: src/Parse/Parse.c.o
.PHONY : src/Parse/Parse.o

# target to build an object file
src/Parse/Parse.c.o:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Parse/Parse.c.o
.PHONY : src/Parse/Parse.c.o

src/Parse/Parse.i: src/Parse/Parse.c.i
.PHONY : src/Parse/Parse.i

# target to preprocess a source file
src/Parse/Parse.c.i:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Parse/Parse.c.i
.PHONY : src/Parse/Parse.c.i

src/Parse/Parse.s: src/Parse/Parse.c.s
.PHONY : src/Parse/Parse.s

# target to generate assembly for a file
src/Parse/Parse.c.s:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/Parse/Parse.c.s
.PHONY : src/Parse/Parse.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/main.c.s
.PHONY : src/main.c.s

src/queue.o: src/queue.c.o
.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i
.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s
.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/LopetteRobot.dir/build.make CMakeFiles/LopetteRobot.dir/src/queue.c.s
.PHONY : src/queue.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LopetteRobot"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/BindingAVR/BindingAVR.o"
	@echo "... src/BindingAVR/BindingAVR.i"
	@echo "... src/BindingAVR/BindingAVR.s"
	@echo "... src/Commande/Commande.o"
	@echo "... src/Commande/Commande.i"
	@echo "... src/Commande/Commande.s"
	@echo "... src/Parse/Parse.o"
	@echo "... src/Parse/Parse.i"
	@echo "... src/Parse/Parse.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

